#!/bin/bash

if [ $(id -u) -ne 0 ]; then
  printf "Install must be run as root. Try 'sudo ./install'\n"
  exit 1
fi

if [ -f /usr/local/lib/libserialport.so.0.0.0 ]; then
  printf "Dependencies already installed. Updating...\n"
fi

cp libs/libserialport* /usr/local/lib/

if [ ! -f /usr/local/lib/libserialport.so.0 ]; then
  ln -s /usr/local/lib/libserialport.so.0.0.0 /usr/local/lib/libserialport.so.0
fi

if [ ! -f /usr/local/lib/libserialport.so ]; then
  ln -s /usr/local/lib/libserialport.so.0.0.0 /usr/local/lib/libserialport.so
fi

chown root:staff /usr/local/lib/libserialport*
